### ISSUE TITLE
PN532 Arduino

### ISSUE THREAD

**Issue by Ecosmos** [don/NDEF#15]
Hello
I have two questions regarding this post, is it possible to use the code to have two PN532 arduino communicate with eachother? Because whenever I try sending a message I always get a failure notification.

The second thing is it possible to have the communication established through I2C as well ?

**Comment by jlkalberer** [comment]
Would it be possible to break up the packet to make I2C work?  
I am using the Grove NFC that only supports I2C and UART.

**Comment by xiongyihui** [comment]
Breaking up the packet will not work.  You can modify Arduino's I2C library to increase its buffer (at least 44 bytes) to make p2p work with I2C. The default buffer length is 32 bytes.

**Comment by jlkalberer** [comment]
Ok. I'm using a Spark Core but I'll try to compile the firmware with that change.

**Comment by helpme1** [comment]
Hi Don,
I got hold of your book, downloaded the code and bought an Adafruit Arduino NFC shield. Things like reading NFC cards worked fine until I tried the NDEC functions. I discovered the problem lies with the I2C interface. Unfortunately, I cannot use SPI for some reason. I tried increasing the i2c buffer size but it did not help. In fact, raising the buffer size caused the Arduino code to hang. Are there any clues how to get your NDEC code to work with I2C? 

@xiongyihui: I tried increasing the buffer size to 44 bytes. It is still too small. When I raised it to around 80 bytes, the code hangs. I am at a loss.

Has anyone got it working before? Maybe I did something wrong. It will be great if those who got it working can post the code. Thanks a lot.

**Comment by don** [comment]
@helpme1 it would be better if you create a new issue for this, rather than adding to a closed issue.

With the Adafruit Shield, you use I2C by default. You need to solder some jumpers for the shield to do SPI with that hardware.

The Adafruit Shield and I2C work for reading and writing NDEF data to NFC tags. You should *not* need to increase the I2C buffer size for read and write. @xiongyihui's comment about the I2C buffer is required for peer-to-peer (LLCP, SNEP). When the Arduino hangs, I find it usually in out of memory, try a smaller buffer and smaller NDEF messages.

See if you can get the [ReadTag](https://github.com/don/NDEF/blob/master/examples/ReadTag/ReadTag.ino), [ReadTagExtended](https://github.com/don/NDEF/blob/master/examples/ReadTagExtended/ReadTagExtended.ino), and [WriteTag](https://github.com/don/NDEF/blob/master/examples/WriteTag/WriteTag.ino) examples working with the Adafruit shield and I2C. If not please [create a new issue](https://github.com/don/NDEF/issues/new) with details about the problem and some code.
