### ISSUE TITLE
NDEF with Adafruit_NFCShield_I2C

### ISSUE THREAD

**Issue by neo4700** [don/NDEF#26]
HI @don 
kindly, i have arduino DUE, and Adafruit PN532 NFC/RFID Shield, and the only library which is compatible (as i heard) is the Adafruit_NFCShield_I2C library at: https://github.com/adafruit/Adafruit_NFCShield_I2C,

 the thing is that i want to use the NDEF library developed by you (interacting with records is easy), but as i heard that it needs some modification to work with Adafruit_NFCShield_I2C library, so can you please help me with that.

Note: the reason im using DUE is because of its large memory

**Comment by neo4700** [comment]
Hello @don 
Kindly , would you plz help me in the above issue?

**Comment by don** [comment]
@neo4700 Sorry for the very late response...

You can use this library with the Arduino Due and the Adafruit NFC Shield. You need to use the Seeed Studio PN532 drivers rather than the Adafruit drivers.

In order to use the Due, you need to jumper SDA and SCL on the Shield to pins to 20 and 21 on the Due. (Alternately pins 4 and 5 on the shield should work too see https://www.arduino.cc/en/Reference/Wire ) 

![nfc-due-jumper-sda-scl](https://cloud.githubusercontent.com/assets/3133/10376421/d544f412-6dcb-11e5-8f8a-1f65b3983804.jpg)
