### ISSUE TITLE
P2P between Arduinos

### ISSUE THREAD

**Issue by jfcgomes** [don/NDEF#37]
Hi!
I am trying get 2 Arduinos to communicate with each other using NFC using your library. 
I made one Arduino the Sender and the other the Receiver, but there no data is being sent. Not sure if I am doing something wrong or if the library is not read it. 
Hope you can shed some light in this problem.

Thanks!!
John

**Comment by don** [comment]
I haven't been able to get P2P to work with 2 Arduino boards. There's something that's missing to let the board know another tag is in range like an Android phone does. At one point I started digging into the specs but didn't find a solution. Maybe the Seeed people know more? You could try https://github.com/Seeed-Studio/PN532

I'm closing this issue since it's really old. Open a new issue if you have more info.
